from pathlib import Path

path = Path('alumno/index.html')
text = path.read_text(encoding='utf-8')
original = text

# Re-run marker: student tracking measurements module.

css_marker = '.video-limit{font-weight:900;color:var(--green-dark)}'
css_insert = r'''.student-measurements{display:grid;gap:16px}.student-measurements-intro{background:linear-gradient(135deg,#f4fbef,#fff);border:1px solid var(--line);border-radius:28px;padding:24px}.student-measurements-intro h3{margin:0 0 8px;color:var(--navy);font-size:24px}.student-measurements-intro p{margin:0;color:var(--muted);line-height:1.5}.measurement-chart-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.measurement-chart-card{background:#fff;border:1px solid var(--line);border-radius:22px;padding:16px;box-shadow:0 12px 28px rgba(24,34,61,.07)}.measurement-chart-title{display:flex;justify-content:space-between;align-items:baseline;gap:10px;margin-bottom:10px}.measurement-chart-title strong{color:var(--navy);font-size:17px}.measurement-chart-title span{color:var(--muted);font-size:12px;font-weight:900}.measurement-chart-svg{width:100%;height:190px;display:block;overflow:visible}.measurement-chart-area{fill:rgba(115,173,19,.16)}.measurement-chart-line{fill:none;stroke:#173f35;stroke-width:4;stroke-linecap:round;stroke-linejoin:round}.measurement-chart-point{fill:var(--green);stroke:#fff;stroke-width:3}.measurement-chart-label,.measurement-chart-date{fill:#173f35;font-size:11px;font-weight:900}.measurement-chart-date{fill:var(--muted);font-size:10px}.measurement-chart-empty{background:#f8fcf6;border:1px dashed rgba(115,173,19,.35);border-radius:18px;padding:18px;color:var(--muted);line-height:1.45}.measurements-list{display:grid;gap:14px}.measurement-card{background:#fff;border:1px solid var(--line);border-radius:24px;padding:18px;display:grid;gap:14px;box-shadow:0 12px 28px rgba(24,34,61,.06)}.measurement-top{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;flex-wrap:wrap}.measurement-date{color:var(--navy);font-size:22px;font-weight:900}.measurement-note{color:var(--muted);margin:4px 0 0;line-height:1.45}.measurement-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.measurement-metric{background:#f4fbef;border:1px solid #e1efd7;border-radius:16px;padding:13px}.measurement-metric span{display:block;color:var(--muted);font-size:12px;font-weight:900;margin-bottom:6px}.measurement-metric strong{color:#173f35;font-size:19px}'''
if css_insert not in text:
    text = text.replace(css_marker, css_marker + css_insert)

text = text.replace('@media(max-width:1060px){.hero,.app{grid-template-columns:1fr}', '@media(max-width:1060px){.hero,.app,.measurement-chart-grid,.measurement-grid{grid-template-columns:1fr}')

old_tracking = '''<section class="panel" id="tracking"><div class="panel-head"><div><h2>Tracking</h2><p>Mediciones y datos útiles para seguir evolución.</p></div></div><div class="card"><div class="data-grid" id="trackingGrid"></div></div></section>'''
new_tracking = '''<section class="panel" id="tracking"><div class="panel-head"><div><h2>Tracking</h2><p>Mediciones y evolución registradas por Yanina.</p></div><span class="tag">Histórico Starfit</span></div><div class="student-measurements"><div class="student-measurements-intro"><h3>Evolución</h3><p>Peso, grasa corporal y músculo esquelético según tus mediciones guardadas.</p></div><div class="measurement-chart-grid" id="studentMeasurementCharts"><div class="measurement-chart-empty">Cargando gráficos de evolución...</div></div><div class="measurements-list" id="studentMeasurementList"><div class="empty">Cargando histórico de mediciones...</div></div></div></section>'''
text = text.replace(old_tracking, new_tracking)
text = text.replace("$('trackingGrid').innerHTML=[data('Peso inicial',s.initial_weight),data('Últimas mediciones',fmtDate(s.last_measurements_date)),data('Días por semana',s.frequency),data('Estado','Seguimiento activo')].join('')", "")

helper = r'''
    const studentMeasurementCharts=document.getElementById('studentMeasurementCharts');const studentMeasurementList=document.getElementById('studentMeasurementList');
    function toMeasurementNumber(value){if(value===null||value===undefined)return null;const n=Number(String(value).replace(',','.').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null}
    function normalizeMeasurementDateValue(value){if(!value)return '';const raw=String(value).trim();const iso=raw.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);if(iso)return `${iso[1]}-${String(iso[2]).padStart(2,'0')}-${String(iso[3]).padStart(2,'0')}`;const monthMap={jan:'01',january:'01',ene:'01',enero:'01',feb:'02',february:'02',febrero:'02',mar:'03',march:'03',marzo:'03',apr:'04',april:'04',abr:'04',abril:'04',may:'05',mayo:'05',jun:'06',june:'06',junio:'06',jul:'07',july:'07',julio:'07',aug:'08',august:'08',ago:'08',agosto:'08',sep:'09',sept:'09',september:'09',septiembre:'09',set:'09',oct:'10',october:'10',octubre:'10',nov:'11',november:'11',noviembre:'11',dec:'12',december:'12',dic:'12',diciembre:'12'};const textMatch=raw.match(/^([A-Za-zÁÉÍÓÚáéíóúñÑ]+)\s+(\d{1,2}),?\s+(\d{2,4})$/);if(textMatch){const key=textMatch[1].toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const month=monthMap[key.slice(0,3)]||monthMap[key];const day=String(textMatch[2]).padStart(2,'0');let year=String(textMatch[3]);if(year.length===2)year=Number(year)>=70?`19${year}`:`20${year}`;if(month)return `${year}-${month}-${day}`}return raw}
    function measurementDateValue(item){return item?.measured_at||item?.measuredAt||item?.measurement_date||item?.date||item?.created_at||''}
    function sortedMeasurementsByDate(items){return [...(items||[])].sort((a,b)=>normalizeMeasurementDateValue(measurementDateValue(a)).localeCompare(normalizeMeasurementDateValue(measurementDateValue(b))))}
    function formatMeasurementDate(value){const normalized=normalizeMeasurementDateValue(value);if(!normalized)return 'Sin fecha';const parts=normalized.slice(0,10).split('-');if(parts.length!==3)return normalized;const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];const month=months[Math.max(0,Math.min(11,Number(parts[1])-1))]||parts[1];return `${month} ${parts[2]}, ${parts[0].slice(-2)}`}
    function metricPoints(measurements,key){return sortedMeasurementsByDate(measurements).map(item=>({label:formatMeasurementDate(measurementDateValue(item)),value:toMeasurementNumber(item[key])})).filter(p=>p.value!==null)}
    function renderMetricChart(config,points){if(!points.length)return `<article class="measurement-chart-card"><div class="measurement-chart-title"><strong>${esc(config.title)}</strong><span>${esc(config.unit)}</span></div><div class="measurement-chart-empty">Todavía no hay datos suficientes para este indicador.</div></article>`;const width=360,height=190,paddingX=34,top=26,bottom=40,usableW=width-paddingX*2,usableH=height-top-bottom;const values=points.map(p=>p.value);let min=Math.min(...values),max=Math.max(...values);if(min===max){min-=1;max+=1}const range=max-min;min-=range*.12;max+=range*.12;const coords=points.map((point,index)=>{const x=points.length===1?width/2:paddingX+(index*usableW/(points.length-1));const y=top+((max-point.value)/(max-min))*usableH;return{...point,x,y}});const line=coords.map((p,i)=>`${i===0?'M':'L'} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' ');const area=`M ${coords[0].x.toFixed(1)} ${(height-bottom).toFixed(1)} L `+coords.map(p=>`${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' L ')+` L ${coords[coords.length-1].x.toFixed(1)} ${(height-bottom).toFixed(1)} Z`;const latest=coords[coords.length-1];return `<article class="measurement-chart-card"><div class="measurement-chart-title"><strong>${esc(config.title)}</strong><span>${esc(latest.value.toFixed(config.decimals).replace('.',','))} ${esc(config.unit)}</span></div><svg class="measurement-chart-svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="Evolución de ${esc(config.title)}"><path class="measurement-chart-area" d="${area}"></path><path class="measurement-chart-line" d="${line}"></path>${coords.map(point=>`<circle class="measurement-chart-point" cx="${point.x.toFixed(1)}" cy="${point.y.toFixed(1)}" r="5"></circle><text class="measurement-chart-label" x="${point.x.toFixed(1)}" y="${(point.y-10).toFixed(1)}" text-anchor="middle">${esc(point.value.toFixed(config.decimals).replace('.',','))}</text><text class="measurement-chart-date" x="${point.x.toFixed(1)}" y="${height-14}" text-anchor="middle">${esc(point.label)}</text>`).join('')}</svg></article>`}
    function renderStudentMeasurements(measurements){const ordered=sortedMeasurementsByDate(measurements);if(studentMeasurementCharts){const configs=[{key:'weight_kg',title:'Peso',unit:'kg',decimals:1},{key:'body_fat_percent',title:'Grasa corporal',unit:'%',decimals:1},{key:'skeletal_muscle_kg',title:'Músculo esquelético',unit:'%',decimals:1}];studentMeasurementCharts.innerHTML=ordered.length?configs.map(c=>renderMetricChart(c,metricPoints(ordered,c.key))).join(''):'<div class="measurement-chart-empty">Todavía no hay mediciones suficientes para graficar evolución.</div>'}if(!studentMeasurementList)return;if(!ordered.length){studentMeasurementList.innerHTML='<div class="empty">Todavía no hay mediciones guardadas.</div>';return}studentMeasurementList.innerHTML=ordered.map(item=>`<article class="measurement-card"><div class="measurement-top"><div><div class="measurement-date">${esc(formatMeasurementDate(measurementDateValue(item)))}</div><p class="measurement-note">${esc(item.trainer_note||'Medición registrada por Yanina.')}</p></div><span class="tag">Medición guardada</span></div><div class="measurement-grid"><div class="measurement-metric"><span>Peso</span><strong>${esc(item.weight_kg||'—')} kg</strong></div><div class="measurement-metric"><span>IMC / BMI</span><strong>${esc(item.bmi||'—')}</strong></div><div class="measurement-metric"><span>Grasa corporal</span><strong>${esc(item.body_fat_percent||'—')}%</strong></div><div class="measurement-metric"><span>Músculo esquelético %</span><strong>${esc(item.skeletal_muscle_kg||'—')}%</strong></div><div class="measurement-metric"><span>Grasa visceral</span><strong>${esc(item.visceral_fat||'—')}</strong></div><div class="measurement-metric"><span>Puntuación</span><strong>${esc(item.body_score||'—')}</strong></div></div></article>`).join('')}
    async function loadStudentMeasurements(){try{const r=await fetch(`${API_BASE}/api/students/${STUDENT_ID}/measurements?cache=${Date.now()}`);if(!r.ok)throw new Error('measurements');const data=await r.json();renderStudentMeasurements(Array.isArray(data)?data:[])}catch(e){console.error(e);if(studentMeasurementCharts)studentMeasurementCharts.innerHTML='<div class="measurement-chart-empty">No se pudieron cargar los gráficos.</div>';if(studentMeasurementList)studentMeasurementList.innerHTML='<div class="empty">No se pudo cargar el histórico de mediciones.</div>'}}
'''
if 'function loadStudentMeasurements()' not in text:
    text = text.replace('    async function loadStudent(){', helper + '\n    async function loadStudent(){')

text = text.replace('async function init(){try{await loadStudent();await loadClasses();renderVideos()}', 'async function init(){try{await loadStudent();await loadClasses();await loadStudentMeasurements();renderVideos()}')

if text == original:
    print('already patched')
else:
    path.write_text(text, encoding='utf-8')
    print('patched student tracking')
